import {
  // Organize
  Merge, Scissors, FilePlus, FileMinus, LayoutGrid, RotateCw, Copy,
  ArrowDownUp, Plus, ArrowRightLeft, Shuffle, Columns, BookOpen,
  Grid3X3, Image as ImageIcon, Ruler, Bookmark as BookmarkIcon,
  Type, ListOrdered, ScanLine, Eye as EyeIcon,
  // Edit
  PenTool, ImagePlus, Shapes, Minus, Pencil, Highlighter, Underline,
  Strikethrough, MessageSquare, StickyNote, Quote, Link2, Eraser,
  ShieldAlert, Search as SearchIcon, Footprints, Hash, Droplets,
  Layers, PaintBucket, Layers2, Stamp, PenLine,
  // Forms
  FileEdit, Square, Radio, ListChecks, Calendar, FileSignature,
  // Convert
  FileText, FileSpreadsheet, Presentation, FileImage, FileCode,
  FileOutput, Archive,
  // Compress
  Minimize2, Gauge, ImageDown, Palette, Trash2, Wrench, Maximize2,
  Move, Crop, Scan,
  // OCR
  ScanText, Languages, Sparkles,
  // Security
  Lock, Unlock, Key, ShieldCheck, ShieldOff, FileX, Bug, Shield,
  // Inspect
  Info, BarChart3, Table2, Network, GitCompare, FileSearch,
  Activity, FileClock, AlertTriangle, CheckCircle2, Printer,
  // Extract
  Download, FileDown, Paperclip, FileOutput as FileOut, Map,
  // AI
  Brain, MessageCircle, Languages as Translate, BookMarked,
  Lightbulb, Target, Quote as QuoteIcon, Briefcase,
  // Workflows
  GitBranch, Play, Save, Import, Filter, Tag, Heart, History,
  RefreshCw, Copy as CopyIcon, Split, Shield as ShieldIcon,
  PlayCircle,
  // Create
  FilePlus2, Type as TypeIcon, FileCode2, Database, Receipt,
  Award, FileBarChart, Image as ImageCreate, QrCode,
  // Developer
  Code2, Boxes, FileCode as FileCodeIcon, Zap, Settings2,
  ShieldQuestion, FileStack, FormInput, Bug as BugIcon,
  FileWarning, Cpu, TestTube, Box, Table, Braces,
  // Generic
  File, Folder,
  LucideIcon,
} from 'lucide-react';

// Category icons
const categoryIcons: Record<string, LucideIcon> = {
  'organize': LayoutGrid,
  'edit': PenTool,
  'forms': FileEdit,
  'convert-from': FileOutput,
  'convert-to': FilePlus2,
  'compress': Minimize2,
  'ocr': ScanText,
  'security': Shield,
  'inspect': SearchIcon,
  'extract': Download,
  'ai': Brain,
  'workflows': GitBranch,
  'create': FilePlus2,
  'developer': Code2,
};

// Tool-specific icons
const toolIcons: Record<string, LucideIcon> = {
  // Organize
  'merge-pdf': Merge,
  'split-pdf': Scissors,
  'extract-pages': FilePlus,
  'delete-pages': FileMinus,
  'reorder-pages': ArrowDownUp,
  'rotate-pages': RotateCw,
  'duplicate-pages': Copy,
  'reverse-pages': ArrowDownUp,
  'insert-blank-pages': Plus,
  'insert-pdf-pages': FilePlus,
  'replace-pages': ArrowRightLeft,
  'move-pages-between': Shuffle,
  'alternate-mix': Columns,
  'split-in-half': Scissors,
  'booklet-imposition': BookOpen,
  'n-up-pages': Grid3X3,
  'poster-tiled': ImageIcon,
  'page-contact-sheet': ImageIcon,
  'split-by-file-size': Ruler,
  'split-by-bookmarks': BookmarkIcon,
  'split-by-text': Type,
  'extract-odd-pages': FilePlus,
  'extract-even-pages': FilePlus,
  'sort-pages-number': ListOrdered,
  'sort-pages-text': ListOrdered,
  'page-labels': BookmarkIcon,
  'page-range-builder': ListOrdered,
  'page-sequence-gen': ListOrdered,
  'rotate-by-detection': ScanLine,
  'blank-page-detector': EyeIcon,

  // Edit
  'edit-pdf-text': PenTool,
  'add-text': Type,
  'add-image': ImagePlus,
  'add-shape': Shapes,
  'add-line-arrow': Minus,
  'freehand-draw': Pencil,
  'highlight-text': Highlighter,
  'underline-text': Underline,
  'strikeout-text': Strikethrough,
  'add-comment': MessageSquare,
  'sticky-note': StickyNote,
  'callout-annotation': Quote,
  'add-link': Link2,
  'edit-links': Link2,
  'whiteout': Eraser,
  'redaction': ShieldAlert,
  'find-replace': SearchIcon,
  'header-footer': Footprints,
  'page-numbers': Hash,
  'bates-numbering': Hash,
  'watermark-text': Droplets,
  'watermark-image': Droplets,
  'background-layer': PaintBucket,
  'foreground-overlay': Layers2,
  'stamp-pdf': Stamp,
  'signature-placement': PenLine,
  'flatten-annotations': Layers,

  // Forms
  'fill-form': FileEdit,
  'create-fillable-form': FileEdit,
  'auto-detect-fields': ScanLine,
  'form-field-inspector': SearchIcon,
  'form-field-editor': FileEdit,
  'form-reset': RefreshCw,
  'form-data-export': Download,
  'form-data-import': FilePlus,
  'signature-draw': PenLine,
  'signature-type': PenLine,
  'signature-image': PenLine,
  'signature-verify': ShieldCheck,
  'signing-request': FileSignature,

  // Convert From
  'pdf-to-word': FileText,
  'pdf-to-excel': FileSpreadsheet,
  'pdf-to-powerpoint': Presentation,
  'pdf-to-images': FileImage,
  'pdf-to-jpg': FileImage,
  'pdf-to-png': FileImage,
  'pdf-to-webp': FileImage,
  'pdf-to-bmp': FileImage,
  'pdf-to-tiff': FileImage,
  'pdf-to-svg': FileCode,
  'pdf-to-html': FileCode,
  'pdf-to-text': FileText,
  'pdf-to-json': FileCode,
  'pdf-to-markdown': FileCode,
  'pdf-to-epub': Archive,
  'pdf-to-odt': FileText,
  'pdf-to-ods': FileSpreadsheet,
  'pdf-to-pdfa': Archive,
  'pdf-to-pdfa-variant': Archive,
  'pdf-to-searchable': ScanText,
  'pdf-to-zip-images': Archive,
  'pdf-images-extractor': FileImage,

  // Convert To
  'jpg-to-pdf': FileImage,
  'png-to-pdf': FileImage,
  'webp-to-pdf': FileImage,
  'heic-to-pdf': FileImage,
  'bmp-to-pdf': FileImage,
  'tiff-to-pdf': FileImage,
  'svg-to-pdf': FileCode,
  'gif-to-pdf': FileImage,
  'doc-to-pdf': FileText,
  'xls-to-pdf': FileSpreadsheet,
  'ppt-to-pdf': Presentation,
  'odt-to-pdf': FileText,
  'txt-to-pdf': FileText,
  'rtf-to-pdf': FileText,
  'html-to-pdf': FileCode,
  'url-to-pdf': FileCode,
  'markdown-to-pdf': FileCode,
  'epub-to-pdf': Archive,
  'publisher-to-pdf': FileText,
  'dicom-to-pdf': FileText,
  'email-to-pdf': FileText,
  'json-to-pdf': FileCode,
  'csv-to-pdf': FileSpreadsheet,
  'xml-to-pdf': FileCode,

  // Compress
  'compress-pdf': Minimize2,
  'custom-compression': Gauge,
  'web-optimize': Zap,
  'downsample-images': ImageDown,
  'jpeg-quality-optimizer': Gauge,
  'images-to-grayscale': Palette,
  'pdf-to-grayscale': Palette,
  'monochrome-optimize': Palette,
  'remove-duplicate-resources': Trash2,
  'subset-fonts': Minimize2,
  'remove-unused-objects': Trash2,
  'rasterize-pdf': ImageIcon,
  'flatten-pdf': Layers,
  'normalize-page-size': Maximize2,
  'change-page-size': Maximize2,
  'fit-content-to-page': Move,
  'margin-crop': Crop,
  'deskew-scan': RotateCw,
  'despeckle-scan': Scan,
  'repair-pdf': Wrench,
  'pdf-version-converter': FileText,
  'pdfa-converter': Archive,
  'pdfa-validator': CheckCircle2,
  'pdfx-preflight': Printer,
  'optimize-fonts': Type,
  'resource-report': BarChart3,

  // OCR
  'ocr-pdf': ScanText,
  'ocr-image-to-pdf': ScanText,
  'ocr-selected-pages': ScanText,
  'ocr-language-selector': Languages,
  'auto-language-detect': Languages,
  'deskew-before-ocr': RotateCw,
  'remove-scan-noise': Scan,
  'searchable-text-layer': ScanText,
  'ocr-text-export': FileText,
  'ocr-confidence-report': BarChart3,
  'layout-aware-ocr': LayoutGrid,
  'table-ocr': Table2,
  'handwriting-ocr': Pencil,

  // Security
  'encrypt-pdf': Lock,
  'decrypt-pdf': Unlock,
  'protect-permissions': ShieldCheck,
  'generate-password': Key,
  'password-strength': ShieldCheck,
  'sanitize-pdf': ShieldOff,
  'remove-metadata': FileX,
  'edit-metadata': FileEdit,
  'remove-javascript': Bug,
  'remove-embedded-files': FileX,
  'remove-annotations': FileX,
  'remove-hidden-content': EyeIcon,
  'remove-links': Link2,
  'flatten-for-sharing': Layers,
  'redact-pdf': ShieldAlert,
  'redaction-audit': FileSearch,
  'security-inspection': ShieldCheck,
  'signature-cert-inspector': ShieldCheck,

  // Inspect
  'pdf-viewer': EyeIcon,
  'pdf-metadata-viewer': Info,
  'page-dimensions': Ruler,
  'font-inspector': Type,
  'image-inspector': ImageIcon,
  'color-usage': Palette,
  'annotation-inspector': MessageSquare,
  'link-inspector': Link2,
  'bookmark-inspector': BookmarkIcon,
  'attachment-inspector': Paperclip,
  'page-structure-inspector': Network,
  'pdf-version-detector': Info,
  'pdf-health-report': Activity,
  'accessibility-checker': EyeIcon,
  'pdfa-validate': CheckCircle2,
  'compare-pdfs': GitCompare,
  'text-compare': GitCompare,
  'pixel-compare': GitCompare,
  'page-by-page-diff': GitCompare,
  'compare-metadata': GitCompare,
  'compare-bookmarks': GitCompare,
  'document-statistics': BarChart3,
  'reading-time': FileClock,
  'keyword-frequency': BarChart3,
  'table-detector': Table2,
  'blank-page-report': EyeIcon,
  'duplicate-page-detector': Copy,
  'orientation-report': RotateCw,
  'print-readiness': Printer,

  // Extract
  'extract-text-blocks': FileDown,
  'extract-all-text': FileText,
  'extract-images': FileImage,
  'extract-attachments': Paperclip,
  'extract-fonts-meta': Type,
  'extract-links': Link2,
  'extract-bookmarks': BookmarkIcon,
  'extract-annotations': MessageSquare,
  'extract-forms': FileEdit,
  'extract-thumbnails': ImageIcon,
  'export-page-map': Map,
  'export-manifest': FileOut,
  'data-extraction-csv': FileSpreadsheet,
  'invoice-extraction': Receipt,
  'bank-statement-extraction': FileSpreadsheet,
  'resume-extraction': FileText,
  'contract-clause-extraction': FileText,

  // AI
  'ai-summarize': BookMarked,
  'ask-pdf': MessageCircle,
  'chat-pdf': MessageCircle,
  'translate-pdf': Translate,
  'rewrite-text': PenTool,
  'explain-section': Lightbulb,
  'generate-outline': ListOrdered,
  'generate-key-points': Target,
  'generate-keywords': Tag,
  'generate-flashcards': Layers,
  'generate-quiz': FileEdit,
  'generate-faq': MessageSquare,
  'generate-executive-brief': Briefcase,
  'generate-action-items': Target,
  'citation-finder': SearchIcon,
  'clause-finder': SearchIcon,
  'table-explanation': Table2,
  'multi-pdf-synthesis': Merge,

  // Workflows
  'batch-runner': Play,
  'batch-download-zip': Archive,
  'workflow-builder': GitBranch,
  'workflow-templates': Save,
  'workflow-import-export': Import,
  'conditional-step': Filter,
  'page-filter-step': Filter,
  'file-naming-template': Tag,
  'preset-manager': Save,
  'favorite-tools': Heart,
  'recent-projects': History,
  'job-history': History,
  'retry-failed-job': RefreshCw,
  'duplicate-job': CopyIcon,
  'multi-stage-output': Split,
  'workflow-validation': ShieldIcon,
  'workflow-simulation': PlayCircle,
  'processing-queue': Layers,

  // Create
  'blank-pdf': FilePlus2,
  'text-to-pdf': TypeIcon,
  'md-to-pdf-create': FileCode2,
  'data-to-pdf': Database,
  'invoice-generator': Receipt,
  'receipt-generator': Receipt,
  'certificate-generator': Award,
  'report-generator': FileBarChart,
  'cover-page-generator': ImageCreate,
  'toc-generator': ListOrdered,
  'bookmark-generator': BookmarkIcon,
  'qr-code-pdf': QrCode,
  'barcode-pdf': BarChart3,
  'letterhead-creator': FileText,

  // Developer
  'pdf-object-stats': Boxes,
  'xref-inspection': FileCodeIcon,
  'object-stream-inspector': FileCodeIcon,
  'linearization-check': Zap,
  'trailer-catalog-inspector': FileSearch,
  'permissions-parser': ShieldQuestion,
  'page-tree-inspector': Network,
  'acroform-inspector': FormInput,
  'js-presence-detector': BugIcon,
  'embedded-file-detector': Paperclip,
  'encrypted-doc-detector': Lock,
  'digital-sig-detector': PenLine,
  'render-stress-test': Cpu,
  'pdf-fuzz-test': TestTube,
  'fixture-generator': Box,
  'capability-matrix': Table,
  'batch-rules-editor': Braces,
};

// Tool-specific colors (dark theme friendly)
const toolColors: Record<string, string> = {
  // Organize - Blue shades
  'merge-pdf': '#3b82f6',
  'split-pdf': '#f97316',
  'extract-pages': '#06b6d4',
  'delete-pages': '#ef4444',
  'reorder-pages': '#8b5cf6',
  'rotate-pages': '#14b8a6',
  'duplicate-pages': '#6366f1',
  'reverse-pages': '#ec4899',
  'insert-blank-pages': '#10b981',
  'insert-pdf-pages': '#0ea5e9',
  'replace-pages': '#f59e0b',
  'move-pages-between': '#a855f7',
  'alternate-mix': '#06b6d4',
  'split-in-half': '#f97316',
  'booklet-imposition': '#8b5cf6',
  'n-up-pages': '#14b8a6',
  'poster-tiled': '#ec4899',
  'page-contact-sheet': '#6366f1',
  'split-by-file-size': '#10b981',
  'split-by-bookmarks': '#0ea5e9',
  'split-by-text': '#f59e0b',
  'extract-odd-pages': '#a855f7',
  'extract-even-pages': '#06b6d4',
  'sort-pages-number': '#3b82f6',
  'sort-pages-text': '#8b5cf6',
  'page-labels': '#14b8a6',
  'page-range-builder': '#ec4899',
  'page-sequence-gen': '#6366f1',
  'rotate-by-detection': '#10b981',
  'blank-page-detector': '#0ea5e9',
  
  // Edit - Purple/Pink shades
  'edit-pdf-text': '#a855f7',
  'add-text': '#ec4899',
  'add-image': '#f43f5e',
  'add-shape': '#d946ef',
  'add-line-arrow': '#c026d3',
  'freehand-draw': '#a855f7',
  'highlight-text': '#fbbf24',
  'underline-text': '#f59e0b',
  'strikeout-text': '#ef4444',
  'add-comment': '#10b981',
  'sticky-note': '#fbbf24',
  'callout-annotation': '#06b6d4',
  'add-link': '#3b82f6',
  'edit-links': '#6366f1',
  'whiteout': '#94a3b8',
  'redaction': '#dc2626',
  'find-replace': '#14b8a6',
  'header-footer': '#8b5cf6',
  'page-numbers': '#0ea5e9',
  'bates-numbering': '#f59e0b',
  'watermark-text': '#06b6d4',
  'watermark-image': '#3b82f6',
  'background-layer': '#a855f7',
  'foreground-overlay': '#ec4899',
  'stamp-pdf': '#ef4444',
  'signature-placement': '#10b981',
  'flatten-annotations': '#6366f1',
  
  // Forms - Rose shades
  'fill-form': '#f43f5e',
  'create-fillable-form': '#ec4899',
  'auto-detect-fields': '#d946ef',
  'form-field-inspector': '#a855f7',
  'form-field-editor': '#c026d3',
  'form-reset': '#14b8a6',
  'form-data-export': '#06b6d4',
  'form-data-import': '#0ea5e9',
  'signature-draw': '#3b82f6',
  'signature-type': '#6366f1',
  'signature-image': '#8b5cf6',
  'signature-verify': '#10b981',
  'signing-request': '#f59e0b',
  
  // Convert From PDF - Office colors
  'pdf-to-word': '#2b579a',
  'pdf-to-excel': '#217346',
  'pdf-to-powerpoint': '#d24726',
  'pdf-to-images': '#f97316',
  'pdf-to-jpg': '#f59e0b',
  'pdf-to-png': '#10b981',
  'pdf-to-webp': '#06b6d4',
  'pdf-to-bmp': '#0ea5e9',
  'pdf-to-tiff': '#3b82f6',
  'pdf-to-svg': '#8b5cf6',
  'pdf-to-html': '#f43f5e',
  'pdf-to-text': '#6366f1',
  'pdf-to-json': '#a855f7',
  'pdf-to-markdown': '#ec4899',
  'pdf-to-epub': '#d946ef',
  'pdf-to-odt': '#c026d3',
  'pdf-to-ods': '#14b8a6',
  'pdf-to-pdfa': '#06b6d4',
  'pdf-to-pdfa-variant': '#0ea5e9',
  'pdf-to-searchable': '#10b981',
  'pdf-to-zip-images': '#f59e0b',
  'pdf-images-extractor': '#f97316',
  
  // Convert To PDF - Office colors
  'jpg-to-pdf': '#f59e0b',
  'png-to-pdf': '#10b981',
  'webp-to-pdf': '#06b6d4',
  'heic-to-pdf': '#0ea5e9',
  'bmp-to-pdf': '#3b82f6',
  'tiff-to-pdf': '#6366f1',
  'svg-to-pdf': '#8b5cf6',
  'gif-to-pdf': '#a855f7',
  'doc-to-pdf': '#2b579a',
  'xls-to-pdf': '#217346',
  'ppt-to-pdf': '#d24726',
  'odt-to-pdf': '#14b8a6',
  'txt-to-pdf': '#6366f1',
  'rtf-to-pdf': '#ec4899',
  'html-to-pdf': '#f43f5e',
  'url-to-pdf': '#d946ef',
  'markdown-to-pdf': '#c026d3',
  'epub-to-pdf': '#a855f7',
  'publisher-to-pdf': '#8b5cf6',
  'dicom-to-pdf': '#3b82f6',
  'email-to-pdf': '#0ea5e9',
  'json-to-pdf': '#06b6d4',
  'csv-to-pdf': '#10b981',
  'xml-to-pdf': '#f59e0b',
  
  // Compress - Orange/Green shades
  'compress-pdf': '#10b981',
  'custom-compression': '#14b8a6',
  'web-optimize': '#06b6d4',
  'downsample-images': '#0ea5e9',
  'jpeg-quality-optimizer': '#f59e0b',
  'images-to-grayscale': '#6b7280',
  'pdf-to-grayscale': '#9ca3af',
  'monochrome-optimize': '#4b5563',
  'remove-duplicate-resources': '#ef4444',
  'subset-fonts': '#f97316',
  'remove-unused-objects': '#dc2626',
  'rasterize-pdf': '#f43f5e',
  'flatten-pdf': '#ec4899',
  'normalize-page-size': '#d946ef',
  'change-page-size': '#c026d3',
  'fit-content-to-page': '#a855f7',
  'margin-crop': '#8b5cf6',
  'deskew-scan': '#6366f1',
  'despeckle-scan': '#4f46e5',
  'repair-pdf': '#10b981',
  'pdf-version-converter': '#14b8a6',
  'pdfa-converter': '#06b6d4',
  'pdfa-validator': '#0ea5e9',
  'pdfx-preflight': '#3b82f6',
  'optimize-fonts': '#6366f1',
  'resource-report': '#8b5cf6',
  
  // OCR - Indigo shades
  'ocr-pdf': '#6366f1',
  'ocr-image-to-pdf': '#818cf8',
  'ocr-selected-pages': '#a5b4fc',
  'ocr-language-selector': '#c7d2fe',
  'auto-language-detect': '#4f46e5',
  'deskew-before-ocr': '#4338ca',
  'remove-scan-noise': '#3730a3',
  'searchable-text-layer': '#312e81',
  'ocr-text-export': '#6366f1',
  'ocr-confidence-report': '#818cf8',
  'layout-aware-ocr': '#a5b4fc',
  'table-ocr': '#c7d2fe',
  'handwriting-ocr': '#4f46e5',
  
  // Security - Red shades
  'encrypt-pdf': '#dc2626',
  'decrypt-pdf': '#ef4444',
  'protect-permissions': '#f87171',
  'generate-password': '#fbbf24',
  'password-strength': '#f59e0b',
  'sanitize-pdf': '#10b981',
  'remove-metadata': '#14b8a6',
  'edit-metadata': '#06b6d4',
  'remove-javascript': '#0ea5e9',
  'remove-embedded-files': '#3b82f6',
  'remove-annotations': '#6366f1',
  'remove-hidden-content': '#8b5cf6',
  'remove-links': '#a855f7',
  'flatten-for-sharing': '#ec4899',
  'redact-pdf': '#dc2626',
  'redaction-audit': '#ef4444',
  'security-inspection': '#f87171',
  'signature-cert-inspector': '#fbbf24',
  
  // Inspect - Slate/Gray shades
  'pdf-viewer': '#64748b',
  'pdf-metadata-viewer': '#94a3b8',
  'page-dimensions': '#cbd5e1',
  'font-inspector': '#e2e8f0',
  'image-inspector': '#f1f5f9',
  'color-usage': '#475569',
  'annotation-inspector': '#334155',
  'link-inspector': '#1e293b',
  'bookmark-inspector': '#64748b',
  'attachment-inspector': '#94a3b8',
  'page-structure-inspector': '#cbd5e1',
  'pdf-version-detector': '#e2e8f0',
  'pdf-health-report': '#f1f5f9',
  'accessibility-checker': '#10b981',
  'pdfa-validate': '#14b8a6',
  'compare-pdfs': '#06b6d4',
  'text-compare': '#0ea5e9',
  'pixel-compare': '#3b82f6',
  'page-by-page-diff': '#6366f1',
  'compare-metadata': '#8b5cf6',
  'compare-bookmarks': '#a855f7',
  'document-statistics': '#ec4899',
  'reading-time': '#f43f5e',
  'keyword-frequency': '#d946ef',
  'table-detector': '#c026d3',
  'blank-page-report': '#a855f7',
  'duplicate-page-detector': '#8b5cf6',
  'orientation-report': '#6366f1',
  'print-readiness': '#4f46e5',
  
  // Extract - Cyan shades
  'extract-text-blocks': '#06b6d4',
  'extract-all-text': '#0891b2',
  'extract-images': '#0e7490',
  'extract-attachments': '#155e75',
  'extract-fonts-meta': '#164e63',
  'extract-links': '#06b6d4',
  'extract-bookmarks': '#0891b2',
  'extract-annotations': '#0e7490',
  'extract-forms': '#155e75',
  'extract-thumbnails': '#164e63',
  'export-page-map': '#06b6d4',
  'export-manifest': '#0891b2',
  'data-extraction-csv': '#10b981',
  'invoice-extraction': '#14b8a6',
  'bank-statement-extraction': '#06b6d4',
  'resume-extraction': '#0ea5e9',
  'contract-clause-extraction': '#3b82f6',
  
  // AI - Violet shades
  'ai-summarize': '#8b5cf6',
  'ask-pdf': '#a78bfa',
  'chat-pdf': '#c4b5fd',
  'translate-pdf': '#ddd6fe',
  'rewrite-text': '#7c3aed',
  'explain-section': '#6d28d9',
  'generate-outline': '#5b21b6',
  'generate-key-points': '#4c1d95',
  'generate-keywords': '#8b5cf6',
  'generate-flashcards': '#a78bfa',
  'generate-quiz': '#c4b5fd',
  'generate-faq': '#ddd6fe',
  'generate-executive-brief': '#7c3aed',
  'generate-action-items': '#6d28d9',
  'citation-finder': '#5b21b6',
  'clause-finder': '#4c1d95',
  'table-explanation': '#8b5cf6',
  'multi-pdf-synthesis': '#a78bfa',
  
  // Workflows - Amber shades
  'batch-runner': '#f59e0b',
  'batch-download-zip': '#fbbf24',
  'workflow-builder': '#fcd34d',
  'workflow-templates': '#fde68a',
  'workflow-import-export': '#fef3c7',
  'conditional-step': '#d97706',
  'page-filter-step': '#b45309',
  'file-naming-template': '#92400e',
  'preset-manager': '#78350f',
  'favorite-tools': '#f59e0b',
  'recent-projects': '#fbbf24',
  'job-history': '#fcd34d',
  'retry-failed-job': '#fde68a',
  'duplicate-job': '#fef3c7',
  'multi-stage-output': '#d97706',
  'workflow-validation': '#b45309',
  'workflow-simulation': '#92400e',
  'processing-queue': '#78350f',
  
  // Create - Emerald shades
  'blank-pdf': '#10b981',
  'text-to-pdf': '#34d399',
  'md-to-pdf-create': '#6ee7b7',
  'data-to-pdf': '#a7f3d0',
  'invoice-generator': '#d1fae5',
  'receipt-generator': '#059669',
  'certificate-generator': '#047857',
  'report-generator': '#065f46',
  'cover-page-generator': '#064e3b',
  'toc-generator': '#10b981',
  'bookmark-generator': '#34d399',
  'qr-code-pdf': '#6ee7b7',
  'barcode-pdf': '#a7f3d0',
  'letterhead-creator': '#d1fae5',
  
  // Developer - Gray shades
  'pdf-object-stats': '#6b7280',
  'xref-inspection': '#9ca3af',
  'object-stream-inspector': '#d1d5db',
  'linearization-check': '#e5e7eb',
  'trailer-catalog-inspector': '#f3f4f6',
  'permissions-parser': '#4b5563',
  'page-tree-inspector': '#374151',
  'acroform-inspector': '#1f2937',
  'js-presence-detector': '#111827',
  'embedded-file-detector': '#6b7280',
  'encrypted-doc-detector': '#9ca3af',
  'digital-sig-detector': '#d1d5db',
  'render-stress-test': '#e5e7eb',
  'pdf-fuzz-test': '#f3f4f6',
  'fixture-generator': '#4b5563',
  'capability-matrix': '#374151',
  'batch-rules-editor': '#1f2937',
};

// Category colors
const categoryColors: Record<string, string> = {
  'organize': '#3b82f6',
  'edit': '#a855f7',
  'forms': '#ec4899',
  'convert-from': '#10b981',
  'convert-to': '#06b6d4',
  'compress': '#f59e0b',
  'ocr': '#6366f1',
  'security': '#ef4444',
  'inspect': '#64748b',
  'extract': '#0891b2',
  'ai': '#8b5cf6',
  'workflows': '#f59e0b',
  'create': '#10b981',
  'developer': '#6b7280',
};

export function getToolIcon(slug: string): LucideIcon {
  return toolIcons[slug] || categoryIcons[slug] || File;
}

export function getCategoryIcon(slug: string): LucideIcon {
  return categoryIcons[slug] || Folder;
}

export function getToolColor(slug: string): string {
  return toolColors[slug] || '#6b7280'; // Default gray
}

export function getCategoryColor(slug: string): string {
  return categoryColors[slug] || '#6b7280'; // Default gray
}
