import {
  // Organize
  Merge, Scissors, FilePlus, FileMinus, LayoutGrid, RotateCw, Copy,
  ArrowDownUp, Plus, ArrowRightLeft, Shuffle, Columns, BookOpen,
  Grid3X3, Image as ImageIcon, Ruler, Bookmark as BookmarkIcon,
  Type, ListOrdered, ScanLine, Eye as EyeIcon,
  // Edit
  PenTool, ImagePlus, Shapes, Minus, Pencil, Highlighter, Underline,
  Strikethrough, MessageSquare, StickyNote, Quote, Link2, Eraser,
  ShieldAlert, Search as SearchIcon, Footprints, Hash, Droplets,
  Layers, PaintBucket, Layers2, Stamp, PenLine,
  // Forms
  FileEdit, Square, Radio, ListChecks, Calendar, FileSignature,
  // Convert
  FileText, FileSpreadsheet, Presentation, FileImage, FileCode,
  FileOutput, FileInput, Archive,
  // Compress
  Minimize2, Gauge, ImageDown, Palette, Trash2, Wrench, Maximize2,
  Move, Crop, Scan,
  // OCR
  ScanText, Languages, Sparkles,
  // Security
  Lock, Unlock, Key, ShieldCheck, ShieldOff, FileX, Bug, Shield,
  // Inspect
  Info, BarChart3, Table2, Network, GitCompare, FileSearch,
  Activity, FileClock, AlertTriangle, CheckCircle2, Printer,
  // Extract
  Download, FileDown, Paperclip, FileOutput as FileOut, Map,
  // AI
  Brain, MessageCircle, Languages as Translate, BookMarked,
  Lightbulb, Target, Quote as QuoteIcon, Briefcase,
  // Workflows
  GitBranch, Play, Save, Import, Filter, Tag, Heart, History,
  RefreshCw, Copy as CopyIcon, Split, Shield as ShieldIcon,
  PlayCircle,
  // Create
  FilePlus2, Type as TypeIcon, FileCode2, Database, Receipt,
  Award, FileBarChart, Image as ImageCreate, QrCode,
  // Developer
  Code2, Boxes, FileCode as FileCodeIcon, Zap, Settings2,
  ShieldQuestion, FileStack, FormInput, Bug as BugIcon,
  FileWarning, Cpu, TestTube, Box, Table, Braces,
  // Generic
  File, Folder,
  LucideIcon,
} from 'lucide-react';

// Category icons
const categoryIcons: Record<string, LucideIcon> = {
  'organize': LayoutGrid,
  'edit': PenTool,
  'forms': FileEdit,
  'pdf-to-office': FileOutput,
  'office-to-pdf': FileInput,
  'convert-from': FileOutput,
  'convert-to': FilePlus2,
  'compress': Minimize2,
  'ocr': ScanText,
  'security': Shield,
  'inspect': SearchIcon,
  'extract': Download,
  'ai': Brain,
  'workflows': GitBranch,
  'create': FilePlus2,
  'developer': Code2,
};

// Tool-specific icons
const toolIcons: Record<string, LucideIcon> = {
  // Organize
  'merge-pdf': Merge,
  'split-pdf': Scissors,
  'extract-pages': FilePlus,
  'delete-pages': FileMinus,
  'reorder-pages': ArrowDownUp,
  'rotate-pages': RotateCw,
  'duplicate-pages': Copy,
  'reverse-pages': ArrowDownUp,
  'insert-blank-pages': Plus,
  'insert-pdf-pages': FilePlus,
  'replace-pages': ArrowRightLeft,
  'move-pages-between': Shuffle,
  'alternate-mix': Columns,
  'split-in-half': Scissors,
  'booklet-imposition': BookOpen,
  'n-up-pages': Grid3X3,
  'poster-tiled': ImageIcon,
  'page-contact-sheet': ImageIcon,
  'split-by-file-size': Ruler,
  'split-by-bookmarks': BookmarkIcon,
  'split-by-text': Type,
  'extract-odd-pages': FilePlus,
  'extract-even-pages': FilePlus,
  'sort-pages-number': ListOrdered,
  'sort-pages-text': ListOrdered,
  'page-labels': BookmarkIcon,
  'page-range-builder': ListOrdered,
  'page-sequence-gen': ListOrdered,
  'rotate-by-detection': ScanLine,
  'blank-page-detector': EyeIcon,

  // Edit
  'edit-pdf-text': PenTool,
  'add-text': Type,
  'add-image': ImagePlus,
  'add-shape': Shapes,
  'add-line-arrow': Minus,
  'freehand-draw': Pencil,
  'highlight-text': Highlighter,
  'underline-text': Underline,
  'strikeout-text': Strikethrough,
  'add-comment': MessageSquare,
  'sticky-note': StickyNote,
  'callout-annotation': Quote,
  'add-link': Link2,
  'edit-links': Link2,
  'whiteout': Eraser,
  'redaction': ShieldAlert,
  'find-replace': SearchIcon,
  'header-footer': Footprints,
  'page-numbers': Hash,
  'bates-numbering': Hash,
  'watermark-text': Droplets,
  'watermark-image': Droplets,
  'background-layer': PaintBucket,
  'foreground-overlay': Layers2,
  'stamp-pdf': Stamp,
  'signature-placement': PenLine,
  'flatten-annotations': Layers,

  // Forms
  'fill-form': FileEdit,
  'create-fillable-form': FileEdit,
  'auto-detect-fields': ScanLine,
  'form-field-inspector': SearchIcon,
  'form-field-editor': FileEdit,
  'form-reset': RefreshCw,
  'form-data-export': Download,
  'form-data-import': FilePlus,
  'signature-draw': PenLine,
  'signature-type': PenLine,
  'signature-image': PenLine,
  'signature-verify': ShieldCheck,
  'signing-request': FileSignature,

  // Convert From
  'pdf-to-word': FileText,
  'pdf-to-excel': FileSpreadsheet,
  'pdf-to-powerpoint': Presentation,
  'pdf-to-images': FileImage,
  'pdf-to-jpg': FileImage,
  'pdf-to-png': FileImage,
  'pdf-to-webp': FileImage,
  'pdf-to-bmp': FileImage,
  'pdf-to-tiff': FileImage,
  'pdf-to-svg': FileCode,
  'pdf-to-html': FileCode,
  'pdf-to-text': FileText,
  'pdf-to-json': FileCode,
  'pdf-to-markdown': FileCode,
  'pdf-to-epub': Archive,
  'pdf-to-odt': FileText,
  'pdf-to-ods': FileSpreadsheet,
  'pdf-to-pdfa': Archive,
  'pdf-to-pdfa-variant': Archive,
  'pdf-to-searchable': ScanText,
  'pdf-to-zip-images': Archive,
  'pdf-images-extractor': FileImage,

  // Convert To
  'jpg-to-pdf': FileImage,
  'png-to-pdf': FileImage,
  'webp-to-pdf': FileImage,
  'heic-to-pdf': FileImage,
  'bmp-to-pdf': FileImage,
  'tiff-to-pdf': FileImage,
  'svg-to-pdf': FileCode,
  'gif-to-pdf': FileImage,
  'doc-to-pdf': FileText,
  'xls-to-pdf': FileSpreadsheet,
  'ppt-to-pdf': Presentation,
  'odt-to-pdf': FileText,
  'txt-to-pdf': FileText,
  'rtf-to-pdf': FileText,
  'html-to-pdf': FileCode,
  'url-to-pdf': FileCode,
  'markdown-to-pdf': FileCode,
  'epub-to-pdf': Archive,
  'publisher-to-pdf': FileText,
  'dicom-to-pdf': FileText,
  'email-to-pdf': FileText,
  'json-to-pdf': FileCode,
  'csv-to-pdf': FileSpreadsheet,
  'xml-to-pdf': FileCode,

  // Compress
  'compress-pdf': Minimize2,
  'custom-compression': Gauge,
  'web-optimize': Zap,
  'downsample-images': ImageDown,
  'jpeg-quality-optimizer': Gauge,
  'images-to-grayscale': Palette,
  'pdf-to-grayscale': Palette,
  'monochrome-optimize': Palette,
  'remove-duplicate-resources': Trash2,
  'subset-fonts': Minimize2,
  'remove-unused-objects': Trash2,
  'rasterize-pdf': ImageIcon,
  'flatten-pdf': Layers,
  'normalize-page-size': Maximize2,
  'change-page-size': Maximize2,
  'fit-content-to-page': Move,
  'margin-crop': Crop,
  'deskew-scan': RotateCw,
  'despeckle-scan': Scan,
  'repair-pdf': Wrench,
  'pdf-version-converter': FileText,
  'pdfa-converter': Archive,
  'pdfa-validator': CheckCircle2,
  'pdfx-preflight': Printer,
  'optimize-fonts': Type,
  'resource-report': BarChart3,

  // OCR
  'ocr-pdf': ScanText,
  'ocr-image-to-pdf': ScanText,
  'ocr-selected-pages': ScanText,
  'ocr-language-selector': Languages,
  'auto-language-detect': Languages,
  'deskew-before-ocr': RotateCw,
  'remove-scan-noise': Scan,
  'searchable-text-layer': ScanText,
  'ocr-text-export': FileText,
  'ocr-confidence-report': BarChart3,
  'layout-aware-ocr': LayoutGrid,
  'table-ocr': Table2,
  'handwriting-ocr': Pencil,

  // Security
  'encrypt-pdf': Lock,
  'decrypt-pdf': Unlock,
  'protect-permissions': ShieldCheck,
  'generate-password': Key,
  'password-strength': ShieldCheck,
  'sanitize-pdf': ShieldOff,
  'remove-metadata': FileX,
  'edit-metadata': FileEdit,
  'remove-javascript': Bug,
  'remove-embedded-files': FileX,
  'remove-annotations': FileX,
  'remove-hidden-content': EyeIcon,
  'remove-links': Link2,
  'flatten-for-sharing': Layers,
  'redact-pdf': ShieldAlert,
  'redaction-audit': FileSearch,
  'security-inspection': ShieldCheck,
  'signature-cert-inspector': ShieldCheck,

  // Inspect
  'pdf-viewer': EyeIcon,
  'pdf-metadata-viewer': Info,
  'page-dimensions': Ruler,
  'font-inspector': Type,
  'image-inspector': ImageIcon,
  'color-usage': Palette,
  'annotation-inspector': MessageSquare,
  'link-inspector': Link2,
  'bookmark-inspector': BookmarkIcon,
  'attachment-inspector': Paperclip,
  'page-structure-inspector': Network,
  'pdf-version-detector': Info,
  'pdf-health-report': Activity,
  'accessibility-checker': EyeIcon,
  'pdfa-validate': CheckCircle2,
  'compare-pdfs': GitCompare,
  'text-compare': GitCompare,
  'pixel-compare': GitCompare,
  'page-by-page-diff': GitCompare,
  'compare-metadata': GitCompare,
  'compare-bookmarks': GitCompare,
  'document-statistics': BarChart3,
  'reading-time': FileClock,
  'keyword-frequency': BarChart3,
  'table-detector': Table2,
  'blank-page-report': EyeIcon,
  'duplicate-page-detector': Copy,
  'orientation-report': RotateCw,
  'print-readiness': Printer,

  // Extract
  'extract-text-blocks': FileDown,
  'extract-all-text': FileText,
  'extract-images': FileImage,
  'extract-attachments': Paperclip,
  'extract-fonts-meta': Type,
  'extract-links': Link2,
  'extract-bookmarks': BookmarkIcon,
  'extract-annotations': MessageSquare,
  'extract-forms': FileEdit,
  'extract-thumbnails': ImageIcon,
  'export-page-map': Map,
  'export-manifest': FileOut,
  'data-extraction-csv': FileSpreadsheet,
  'invoice-extraction': Receipt,
  'bank-statement-extraction': FileSpreadsheet,
  'resume-extraction': FileText,
  'contract-clause-extraction': FileText,

  // AI
  'ai-summarize': BookMarked,
  'ask-pdf': MessageCircle,
  'chat-pdf': MessageCircle,
  'translate-pdf': Translate,
  'rewrite-text': PenTool,
  'explain-section': Lightbulb,
  'generate-outline': ListOrdered,
  'generate-key-points': Target,
  'generate-keywords': Tag,
  'generate-flashcards': Layers,
  'generate-quiz': FileEdit,
  'generate-faq': MessageSquare,
  'generate-executive-brief': Briefcase,
  'generate-action-items': Target,
  'citation-finder': SearchIcon,
  'clause-finder': SearchIcon,
  'table-explanation': Table2,
  'multi-pdf-synthesis': Merge,

  // Workflows
  'batch-runner': Play,
  'batch-download-zip': Archive,
  'workflow-builder': GitBranch,
  'workflow-templates': Save,
  'workflow-import-export': Import,
  'conditional-step': Filter,
  'page-filter-step': Filter,
  'file-naming-template': Tag,
  'preset-manager': Save,
  'favorite-tools': Heart,
  'recent-projects': History,
  'job-history': History,
  'retry-failed-job': RefreshCw,
  'duplicate-job': CopyIcon,
  'multi-stage-output': Split,
  'workflow-validation': ShieldIcon,
  'workflow-simulation': PlayCircle,
  'processing-queue': Layers,

  // Create
  'blank-pdf': FilePlus2,
  'text-to-pdf': TypeIcon,
  'md-to-pdf-create': FileCode2,
  'data-to-pdf': Database,
  'invoice-generator': Receipt,
  'receipt-generator': Receipt,
  'certificate-generator': Award,
  'report-generator': FileBarChart,
  'cover-page-generator': ImageCreate,
  'toc-generator': ListOrdered,
  'bookmark-generator': BookmarkIcon,
  'qr-code-pdf': QrCode,
  'barcode-pdf': BarChart3,
  'letterhead-creator': FileText,

  // Developer
  'pdf-object-stats': Boxes,
  'xref-inspection': FileCodeIcon,
  'object-stream-inspector': FileCodeIcon,
  'linearization-check': Zap,
  'trailer-catalog-inspector': FileSearch,
  'permissions-parser': ShieldQuestion,
  'page-tree-inspector': Network,
  'acroform-inspector': FormInput,
  'js-presence-detector': BugIcon,
  'embedded-file-detector': Paperclip,
  'encrypted-doc-detector': Lock,
  'digital-sig-detector': PenLine,
  'render-stress-test': Cpu,
  'pdf-fuzz-test': TestTube,
  'fixture-generator': Box,
  'capability-matrix': Table,
  'batch-rules-editor': Braces,
};

export function getToolIcon(slug: string): LucideIcon {
  return toolIcons[slug] || categoryIcons[slug] || File;
}

export function getCategoryIcon(slug: string): LucideIcon {
  return categoryIcons[slug] || Folder;
}
