import { ToolDefinition } from '../../types/tool';

export const toolRegistry: ToolDefinition[] = [
  // MERGE & SPLIT
  {
    slug: 'merge-pdf',
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into a single document',
    category: 'merge-split',
    icon: 'Merge',
    capability: 'browser-ready',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 200,
    options: [],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: true,
  },
  {
    slug: 'split-pdf',
    title: 'Split PDF',
    description: 'Extract pages or split PDF into multiple files',
    category: 'merge-split',
    icon: 'Scissors',
    capability: 'browser-ready',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 200,
    options: [
      { key: 'mode', label: 'Split Mode', type: 'select', default: 'ranges', options: [{ value: 'ranges', label: 'Page Ranges' }, { value: 'each', label: 'Every Page' }, { value: 'size', label: 'By File Size' }] },
      { key: 'ranges', label: 'Page Ranges', type: 'text', default: '1-3, 4-6' },
    ],
    outputType: 'application/pdf',
    outputMultiple: true,
    supportsBatch: false,
    supportsChaining: true,
  },
  // CONVERT
  {
    slug: 'pdf-to-word',
    title: 'PDF to Word',
    description: 'Convert PDF documents to editable Word files',
    category: 'convert',
    icon: 'FileText',
    capability: 'backend-required',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'format', label: 'Output Format', type: 'select', default: 'docx', options: [{ value: 'docx', label: 'DOCX' }, { value: 'doc', label: 'DOC' }] },
    ],
    outputType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: false,
  },
  {
    slug: 'word-to-pdf',
    title: 'Word to PDF',
    description: 'Convert Word documents to PDF',
    category: 'convert',
    icon: 'FileType',
    capability: 'backend-required',
    acceptsMultiple: true,
    acceptedTypes: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/msword'],
    maxFileSizeMB: 100,
    options: [],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: true,
  },
  {
    slug: 'pdf-to-image',
    title: 'PDF to Image',
    description: 'Convert PDF pages to JPG or PNG images',
    category: 'convert',
    icon: 'Image',
    capability: 'browser-ready',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'format', label: 'Image Format', type: 'select', default: 'png', options: [{ value: 'png', label: 'PNG' }, { value: 'jpeg', label: 'JPEG' }] },
      { key: 'dpi', label: 'Resolution (DPI)', type: 'select', default: '150', options: [{ value: '72', label: '72 DPI' }, { value: '150', label: '150 DPI' }, { value: '300', label: '300 DPI' }] },
      { key: 'pages', label: 'Pages', type: 'text', default: 'all' },
    ],
    outputType: 'image/png',
    outputMultiple: true,
    supportsBatch: false,
    supportsChaining: false,
  },
  {
    slug: 'image-to-pdf',
    title: 'Image to PDF',
    description: 'Convert images (JPG, PNG) to PDF',
    category: 'convert',
    icon: 'FileImage',
    capability: 'browser-ready',
    acceptsMultiple: true,
    acceptedTypes: ['image/jpeg', 'image/png', 'image/webp'],
    maxFileSizeMB: 50,
    options: [
      { key: 'pageSize', label: 'Page Size', type: 'select', default: 'fit', options: [{ value: 'fit', label: 'Fit to Image' }, { value: 'a4', label: 'A4' }, { value: 'letter', label: 'Letter' }] },
      { key: 'orientation', label: 'Orientation', type: 'select', default: 'auto', options: [{ value: 'auto', label: 'Auto' }, { value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape' }] },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: true,
  },
  {
    slug: 'pdf-to-html',
    title: 'PDF to HTML',
    description: 'Convert PDF to HTML preserving layout',
    category: 'convert',
    icon: 'Code',
    capability: 'backend-required',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [],
    outputType: 'text/html',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: false,
  },
  {
    slug: 'pdf-to-markdown',
    title: 'PDF to Markdown',
    description: 'Convert PDF content to Markdown format',
    category: 'convert',
    icon: 'FileCode',
    capability: 'ai-required',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'headings', label: 'Detect Headings', type: 'boolean', default: true },
      { key: 'tables', label: 'Convert Tables', type: 'boolean', default: true },
    ],
    outputType: 'text/markdown',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: false,
  },
  // COMPRESS
  {
    slug: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality',
    category: 'compress',
    icon: 'Minimize2',
    capability: 'browser-partial',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 500,
    options: [
      { key: 'level', label: 'Compression Level', type: 'select', default: 'recommended', options: [{ value: 'low', label: 'Low (Best Quality)' }, { value: 'recommended', label: 'Recommended' }, { value: 'high', label: 'High (Smallest Size)' }] },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: true,
  },
  // EDIT
  {
    slug: 'edit-pdf',
    title: 'Edit PDF',
    description: 'Add text, images, shapes, and annotations to PDF',
    category: 'edit',
    icon: 'Edit3',
    capability: 'browser-partial',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: true,
  },
  {
    slug: 'add-watermark',
    title: 'Add Watermark',
    description: 'Add text or image watermark to PDF pages',
    category: 'edit',
    icon: 'Droplets',
    capability: 'browser-ready',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'text', label: 'Watermark Text', type: 'text', default: 'CONFIDENTIAL' },
      { key: 'opacity', label: 'Opacity', type: 'range', default: 0.5, min: 0.1, max: 1, step: 0.1 },
      { key: 'rotation', label: 'Rotation', type: 'number', default: 45 },
      { key: 'position', label: 'Position', type: 'select', default: 'center', options: [{ value: 'center', label: 'Center' }, { value: 'top-left', label: 'Top Left' }, { value: 'top-right', label: 'Top Right' }, { value: 'bottom-left', label: 'Bottom Left' }, { value: 'bottom-right', label: 'Bottom Right' }] },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: true,
  },
  {
    slug: 'page-numbers',
    title: 'Add Page Numbers',
    description: 'Insert page numbers into PDF documents',
    category: 'edit',
    icon: 'Hash',
    capability: 'browser-ready',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'position', label: 'Position', type: 'select', default: 'bottom-center', options: [{ value: 'bottom-center', label: 'Bottom Center' }, { value: 'bottom-right', label: 'Bottom Right' }, { value: 'bottom-left', label: 'Bottom Left' }, { value: 'top-center', label: 'Top Center' }, { value: 'top-right', label: 'Top Right' }, { value: 'top-left', label: 'Top Left' }] },
      { key: 'startFrom', label: 'Start From', type: 'number', default: 1 },
      { key: 'format', label: 'Format', type: 'select', default: 'number', options: [{ value: 'number', label: '1, 2, 3...' }, { value: 'dash', label: '- 1 -' }, { value: 'page', label: 'Page 1' }, { value: 'of', label: 'Page 1 of N' }] },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: true,
  },
  // SECURITY
  {
    slug: 'protect-pdf',
    title: 'Protect PDF',
    description: 'Add password protection to PDF files',
    category: 'security',
    icon: 'Lock',
    capability: 'browser-ready',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'userPassword', label: 'User Password', type: 'text', default: '' },
      { key: 'ownerPassword', label: 'Owner Password', type: 'text', default: '' },
      { key: 'permissions', label: 'Restrictions', type: 'select', default: 'none', options: [{ value: 'none', label: 'No Restrictions' }, { value: 'no-print', label: 'No Printing' }, { value: 'no-copy', label: 'No Copying' }, { value: 'no-edit', label: 'No Editing' }, { value: 'all', label: 'All Restrictions' }] },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: true,
  },
  {
    slug: 'unlock-pdf',
    title: 'Unlock PDF',
    description: 'Remove password protection from PDF files',
    category: 'security',
    icon: 'Unlock',
    capability: 'browser-ready',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'password', label: 'Password', type: 'text', default: '' },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: true,
  },
  {
    slug: 'sign-pdf',
    title: 'Sign PDF',
    description: 'Add electronic signature to PDF documents',
    category: 'security',
    icon: 'PenTool',
    capability: 'browser-partial',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'signatureType', label: 'Signature Type', type: 'select', default: 'draw', options: [{ value: 'draw', label: 'Draw' }, { value: 'type', label: 'Type' }, { value: 'image', label: 'Upload Image' }] },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: true,
  },
  // ORGANIZE
  {
    slug: 'rotate-pdf',
    title: 'Rotate PDF',
    description: 'Rotate PDF pages to correct orientation',
    category: 'organize',
    icon: 'RotateCw',
    capability: 'browser-ready',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 200,
    options: [
      { key: 'angle', label: 'Rotation', type: 'select', default: '90', options: [{ value: '90', label: '90° Clockwise' }, { value: '180', label: '180°' }, { value: '270', label: '90° Counter-clockwise' }] },
      { key: 'pages', label: 'Apply To', type: 'select', default: 'all', options: [{ value: 'all', label: 'All Pages' }, { value: 'even', label: 'Even Pages' }, { value: 'odd', label: 'Odd Pages' }, { value: 'custom', label: 'Custom Range' }] },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: true,
  },
  {
    slug: 'reorder-pages',
    title: 'Reorder Pages',
    description: 'Rearrange, delete, or duplicate PDF pages',
    category: 'organize',
    icon: 'LayoutGrid',
    capability: 'browser-ready',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 200,
    options: [],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: true,
  },
  // OCR
  {
    slug: 'ocr-pdf',
    title: 'OCR PDF',
    description: 'Make scanned PDFs searchable with OCR',
    category: 'ocr',
    icon: 'ScanText',
    capability: 'backend-required',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'language', label: 'Language', type: 'select', default: 'eng', options: [{ value: 'eng', label: 'English' }, { value: 'spa', label: 'Spanish' }, { value: 'fra', label: 'French' }, { value: 'deu', label: 'German' }, { value: 'chi', label: 'Chinese' }] },
      { key: 'mode', label: 'Mode', type: 'select', default: 'searchable', options: [{ value: 'searchable', label: 'Searchable PDF' }, { value: 'text', label: 'Extract Text Only' }] },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: true,
  },
  // EXTRACT
  {
    slug: 'extract-text',
    title: 'Extract Text',
    description: 'Extract all text content from PDF',
    category: 'extract',
    icon: 'Type',
    capability: 'browser-ready',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'format', label: 'Output Format', type: 'select', default: 'txt', options: [{ value: 'txt', label: 'Plain Text' }, { value: 'csv', label: 'CSV' }] },
    ],
    outputType: 'text/plain',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: false,
  },
  {
    slug: 'extract-images',
    title: 'Extract Images',
    description: 'Extract all images from PDF document',
    category: 'extract',
    icon: 'ImagePlus',
    capability: 'browser-partial',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'format', label: 'Output Format', type: 'select', default: 'png', options: [{ value: 'png', label: 'PNG' }, { value: 'jpeg', label: 'JPEG' }] },
    ],
    outputType: 'image/png',
    outputMultiple: true,
    supportsBatch: false,
    supportsChaining: false,
  },
  {
    slug: 'extract-tables',
    title: 'Extract Tables',
    description: 'Detect and extract tables from PDF',
    category: 'extract',
    icon: 'Table',
    capability: 'ai-required',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'format', label: 'Output Format', type: 'select', default: 'csv', options: [{ value: 'csv', label: 'CSV' }, { value: 'xlsx', label: 'Excel' }, { value: 'json', label: 'JSON' }] },
    ],
    outputType: 'text/csv',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: false,
  },
  // INSPECT
  {
    slug: 'pdf-info',
    title: 'PDF Info',
    description: 'View detailed PDF metadata and properties',
    category: 'inspect',
    icon: 'Info',
    capability: 'browser-ready',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 200,
    options: [],
    outputType: 'text/json',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: false,
  },
  {
    slug: 'pdf-structure',
    title: 'PDF Structure',
    description: 'Inspect internal PDF structure and objects',
    category: 'inspect',
    icon: 'GitBranch',
    capability: 'browser-partial',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 200,
    options: [],
    outputType: 'text/json',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: false,
  },
  // COMPARE
  {
    slug: 'compare-pdf',
    title: 'Compare PDF',
    description: 'Find differences between two PDF documents',
    category: 'compare',
    icon: 'GitCompare',
    capability: 'browser-partial',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'mode', label: 'Compare Mode', type: 'select', default: 'text', options: [{ value: 'text', label: 'Text Comparison' }, { value: 'visual', label: 'Visual Overlay' }] },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: false,
  },
  // FORMS
  {
    slug: 'fill-form',
    title: 'Fill PDF Form',
    description: 'Fill in interactive PDF form fields',
    category: 'forms',
    icon: 'Edit',
    capability: 'browser-ready',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: true,
  },
  {
    slug: 'flatten-form',
    title: 'Flatten PDF',
    description: 'Flatten form fields and annotations',
    category: 'forms',
    icon: 'Layers',
    capability: 'browser-ready',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: true,
  },
  // AI
  {
    slug: 'summarize-pdf',
    title: 'Summarize PDF',
    description: 'AI-powered document summarization',
    category: 'ai',
    icon: 'Brain',
    capability: 'ai-required',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'length', label: 'Summary Length', type: 'select', default: 'medium', options: [{ value: 'short', label: 'Short' }, { value: 'medium', label: 'Medium' }, { value: 'detailed', label: 'Detailed' }] },
    ],
    outputType: 'text/plain',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: false,
  },
  {
    slug: 'ask-pdf',
    title: 'Ask PDF',
    description: 'Ask questions about your PDF content',
    category: 'ai',
    icon: 'MessageCircle',
    capability: 'ai-required',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'question', label: 'Your Question', type: 'text', default: '' },
    ],
    outputType: 'text/plain',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: false,
  },
  {
    slug: 'translate-pdf',
    title: 'Translate PDF',
    description: 'Translate PDF content to another language',
    category: 'ai',
    icon: 'Languages',
    capability: 'ai-required',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'targetLanguage', label: 'Target Language', type: 'select', default: 'es', options: [{ value: 'es', label: 'Spanish' }, { value: 'fr', label: 'French' }, { value: 'de', label: 'German' }, { value: 'it', label: 'Italian' }, { value: 'pt', label: 'Portuguese' }, { value: 'zh', label: 'Chinese' }, { value: 'ja', label: 'Japanese' }, { value: 'ar', label: 'Arabic' }] },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: true,
  },
  // OPTIMIZE
  {
    slug: 'pdf-to-pdfa',
    title: 'PDF to PDF/A',
    description: 'Convert to PDF/A for long-term archiving',
    category: 'optimize',
    icon: 'Archive',
    capability: 'backend-required',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 200,
    options: [
      { key: 'standard', label: 'PDF/A Standard', type: 'select', default: '2b', options: [{ value: '1b', label: 'PDF/A-1b' }, { value: '2b', label: 'PDF/A-2b' }, { value: '3b', label: 'PDF/A-3b' }] },
    ],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: true,
  },
  {
    slug: 'repair-pdf',
    title: 'Repair PDF',
    description: 'Attempt to repair damaged or corrupted PDFs',
    category: 'optimize',
    icon: 'Wrench',
    capability: 'browser-partial',
    acceptsMultiple: true,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 200,
    options: [],
    outputType: 'application/pdf',
    outputMultiple: false,
    supportsBatch: true,
    supportsChaining: true,
  },
  // ACCESSIBILITY
  {
    slug: 'pdf-a11y-check',
    title: 'Accessibility Check',
    description: 'Validate PDF for accessibility compliance',
    category: 'accessibility',
    icon: 'Eye',
    capability: 'backend-required',
    acceptsMultiple: false,
    acceptedTypes: ['application/pdf'],
    maxFileSizeMB: 100,
    options: [
      { key: 'standard', label: 'Standard', type: 'select', default: 'wcag21', options: [{ value: 'wcag21', label: 'WCAG 2.1' }, { value: 'pdfua', label: 'PDF/UA' }, { value: 'tagged', label: 'Tagged PDF' }] },
    ],
    outputType: 'text/json',
    outputMultiple: false,
    supportsBatch: false,
    supportsChaining: false,
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return toolRegistry.find(t => t.slug === slug);
}

export function getToolsByCategory(category: string): ToolDefinition[] {
  return toolRegistry.filter(t => t.category === category);
}

export function searchTools(query: string): ToolDefinition[] {
  const q = query.toLowerCase();
  return toolRegistry.filter(t =>
    t.title.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q) ||
    t.category.toLowerCase().includes(q)
  );
}
